# Generated by Django 5.1.3 on 2024-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_time',
            field=models.CharField(max_length=10),
        ),
    ]
