# Generated by Django 5.1.3 on 2024-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='area',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outputcontrol',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
