# Generated by Django 5.1.3 on 2024-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_accesscontrol_active_area_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
