# Generated by Django 5.1.3 on 2024-11-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputcontrol',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outputcontrol',
            name='status',
            field=models.CharField(choices=[('gone', 'Ketgan'), ('failed', 'Failed')], max_length=20),
        ),
    ]
