# Generated by Django 5.1.3 on 2024-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_accesscontrol_area_outputcontrol_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='latitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='longitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_time',
            field=models.CharField(max_length=110),
        ),
    ]
