# Generated by Django 5.1.3 on 2025-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_accesscontrol_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/access_control'),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='outputcontrol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/output_control'),
        ),
        migrations.AlterField(
            model_name='outputcontrol',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='outputcontrol',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
